In [25]:
from keras.applications.vgg16 import VGG16
from keras.layers import Dense,Dropout
from keras.models import Model, Sequential
from keras.callbacks import EarlyStopping
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.metrics import log_loss,roc_auc_score, roc_curve
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [54]:
train = pd.read_csv('C:\\Users\\odoru\\SIGNATE_time_deposit_account\\train.csv')
test = pd.read_csv('C:\\Users\\odoru\\SIGNATE_time_deposit_account\\test.csv')
submit = pd.read_csv('C:\\Users\\odoru\\SIGNATE_time_deposit_account\\head_submit_sample.csv')

In [55]:
#jobの欠損値処理
test.replace({'job': {'unknown':'blue-collar'}}, inplace=True)

cat_cols = ['job','marital','education','default','housing','loan','contact','month']

#one-hot-encoding
all_x = pd.concat([train,test])
all_x = pd.get_dummies(all_x, columns=cat_cols)

train = all_x.iloc[:train.shape[0], :].reset_index(drop=True)
test = all_x.iloc[train.shape[0]:, :].reset_index(drop=True)

In [58]:
un_df =  train.loc[train['poutcome'] == 'unknown']
df = train.loc[train['poutcome'] != 'unknown']

un_df.drop(['poutcome','y'], axis = 1, inplace =True)
df.drop(['y'], axis = 1, inplace =True)


df = pd.get_dummies(df, 'poutcome')

In [70]:
df_x = df.iloc[:,1:46]
df_y = df.loc[:,['poutcome_failure','poutcome_other','poutcome_success']]
df_test_x = un_df.drop(['id'] ,axis = 1)

In [73]:
#hold out 法
kf = KFold(n_splits=4, shuffle=True, random_state=71)
tr_idx, va_idx = list(kf.split(df_x))[0]
tr_x,va_x = df_x.iloc[tr_idx], df_x.iloc[va_idx]
tr_y,va_y = df_y.iloc[tr_idx], df_y.iloc[va_idx]

In [74]:
tr_x

,age,balance,day,duration,campaign,pdays,previous,job_admin.,job_blue-collar,job_entrepreneur,...,month_aug,month_feb,month_jan,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep
0,31,12294,21,101,3,498,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,35,12252,11,351,1,826,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,31,99121,16,658,2,120,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,32,7958,28,101,1,525,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
16,31,37071,12,523,2,831,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27041,32,89447,28,207,2,460,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
27043,31,81059,20,101,3,148,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27060,37,42553,12,197,1,546,2,1,0,0,...,0,0,0,0,0,0,0,0,0,0
27076,32,85647,28,101,4,144,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
27086,35,97298,20,87,1,867,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [75]:
scaler = StandardScaler()
tr_x = scaler.fit_transform(tr_x)
va_x = scaler.fit_transform(va_x)
df_test_x = scaler.fit_transform(df_test_x)

In [76]:
tr_x.shape

(3000, 45)

In [77]:
model = Sequential()
model.add(Dense(256,activation='relu',input_shape=(df_x.shape[1],)))
model.add(Dropout(0.2))
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy',
             optimizer ='adam', metrics=['accuracy'])

batch_size = 128
epochs = 100
early_stopping = EarlyStopping(monitor = 'val_loss', patience = 20, restore_best_weights=True)


history  = model.fit(tr_x,tr_y,
                    batch_size=batch_size, epochs=epochs,
                    verbose=1,validation_data=(va_x,va_y),
                    callbacks = early_stopping)

va_pred = model.predict(va_x)
score = log_loss(va_y,va_pred, eps=1e-7)
print(score)

Epoch 1/100
24/24 [==============================] - 0s 10ms/step - loss: 0.5456 - accuracy: 0.6423 - val_loss: 0.4705 - val_accuracy: 0.6953
Epoch 2/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4722 - accuracy: 0.6777 - val_loss: 0.4402 - val_accuracy: 0.7033
Epoch 3/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4515 - accuracy: 0.6860 - val_loss: 0.4342 - val_accuracy: 0.7153
Epoch 4/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4422 - accuracy: 0.6943 - val_loss: 0.4354 - val_accuracy: 0.7053
Epoch 5/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4346 - accuracy: 0.7037 - val_loss: 0.4297 - val_accuracy: 0.7093
Epoch 6/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4282 - accuracy: 0.7043 - val_loss: 0.4284 - val_accuracy: 0.7133
Epoch 7/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4242 - accuracy: 0.7107 - val_loss: 0.4298 - val_accuracy: 0.7143
Epoch 8/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4192 - accuracy: 0.7130 - val_loss: 0.4323 - val_accuracy: 0.7103
Epoch 9/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4137 - accuracy: 0.7217 - val_loss: 0.4313 - val_accuracy: 0.7113
Epoch 10/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4087 - accuracy: 0.7297 - val_loss: 0.4305 - val_accuracy: 0.7083
Epoch 11/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4045 - accuracy: 0.7200 - val_loss: 0.4333 - val_accuracy: 0.7093
Epoch 12/100
24/24 [==============================] - 0s 5ms/step - loss: 0.4010 - accuracy: 0.7287 - val_loss: 0.4355 - val_accuracy: 0.7053
Epoch 13/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3980 - accuracy: 0.7287 - val_loss: 0.4342 - val_accuracy: 0.7083
Epoch 14/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3898 - accuracy: 0.7430 - val_loss: 0.4339 - val_accuracy: 0.7093
Epoch 15/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3843 - accuracy: 0.7453 - val_loss: 0.4399 - val_accuracy: 0.6973
Epoch 16/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3808 - accuracy: 0.7447 - val_loss: 0.4425 - val_accuracy: 0.7053
Epoch 17/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3770 - accuracy: 0.7457 - val_loss: 0.4418 - val_accuracy: 0.7043
Epoch 18/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3682 - accuracy: 0.7520 - val_loss: 0.4465 - val_accuracy: 0.6993
Epoch 19/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3687 - accuracy: 0.7480 - val_loss: 0.4482 - val_accuracy: 0.6963
Epoch 20/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3653 - accuracy: 0.7523 - val_loss: 0.4499 - val_accuracy: 0.6943
Epoch 21/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3596 - accuracy: 0.7597 - val_loss: 0.4495 - val_accuracy: 0.6933
Epoch 22/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3507 - accuracy: 0.7623 - val_loss: 0.4556 - val_accuracy: 0.7013
Epoch 23/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3511 - accuracy: 0.7680 - val_loss: 0.4561 - val_accuracy: 0.6913
Epoch 24/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3476 - accuracy: 0.7697 - val_loss: 0.4579 - val_accuracy: 0.6973
Epoch 25/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3427 - accuracy: 0.7820 - val_loss: 0.4604 - val_accuracy: 0.6913
Epoch 26/100
24/24 [==============================] - 0s 5ms/step - loss: 0.3433 - accuracy: 0.7777 - val_loss: 0.4578 - val_accuracy: 0.6913
0.7034777939118646